func f(some_str){
  try{
    print("in f try");
    raise "x";
  }
  catch "x"{
    print("caught ", some_str);
    raise "why not";
  }
}

func main(){
var y;
var z;
y = "why not";
z=y;
f("hello");
}

/*
*OUT*
in f try
caught hello
ErrorType.FAULT_ERROR
*OUT*
*/